server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-db
feign:
  hystrix:
    enabled: false
