server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

feign:
  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 
